origin:
  - 41.68731887943349
  - -8.847724961186827
  - 100
windTurbine_0:
  type: windTurbine
  pose:
    xyz:
      - 184
      - 21.1
      - 0
    rpy:
      - 0
      - 0
      - 0
windTurbine_1:
  type: windTurbine
  pose:
    xyz:
      - -294
      - -7.1
      - 0
    rpy:
      - 0
      - 0
      - 0
windTurbine_2:
  type: windTurbine
  pose:
    xyz:
      - -292.4
      - -35.7
      - 0
    rpy:
      - 0
      - 0
      - 0
windTurbine_3:
  type: windTurbine
  pose:
    xyz:
      - -291
      - -65.5
      - 0
    rpy:
      - 0
      - 0
      - 0
windTurbine_4:
  type: windTurbine
  pose:
    xyz:
      - -292.3
      - -95.1
      - 0
    rpy:
      - 0
      - 0
      - 0
windTurbine_5:
  type: windTurbine
  pose:
    xyz:
      - -300.2
      - -124.2
      - 0
    rpy:
      - 0
      - 0
      - 0
windTurbine_6:
  type: windTurbine
  pose:
    xyz:
      - -310.4
      - -153.3
      - 0
    rpy:
      - 0
      - 0
      - 0
windTurbine_7:
  type: windTurbine
  pose:
    xyz:
      - -328.5
      - -8.5
      - 0
    rpy:
      - 0
      - 0
      - 0
windTurbine_8:
  type: windTurbine
  pose:
    xyz:
      - -326.9
      - -37.7
      - 0
    rpy:
      - 0
      - 0
      - 0
windTurbine_9:
  type: windTurbine
  pose:
    xyz:
      - -326.9
      - -63.6
      - 0
    rpy:
      - 0
      - 0
      - 0
windTurbine_10:
  type: windTurbine
  pose:
    xyz:
      - -325.8
      - -91.7
      - 0
    rpy:
      - 0
      - 0
      - 0
windTurbine_11:
  type: windTurbine
  pose:
    xyz:
      - -329.1
      - -123.7
      - 0
    rpy:
      - 0
      - 0
      - 0
windTurbine_12:
  type: windTurbine
  pose:
    xyz:
      - -339
      - -153.5
      - 0
    rpy:
      - 0
      - 0
      - 0
base_13:
  type: base
  pose:
    xyz:
      - -3.2
      - 2.9
      - 0
    rpy:
      - 0
      - 0
      - 0
px4_3:
  {
    type: drone,
    ns: px4_3,
    id: 2,
    pose: { xyz: [-3.2, 2.9, 0], rpy: [0, 0, 0] },
  }
